### PR TITLE
Removes the hardcoded path for input.nml (NOAA-GFDL#795)

### PR DESCRIPTION
**Pull request by mathomp4**
* Added option to specify an alt_input_nml_path to fms_init, and therefore mpp_init

* Edit read_input_nml call to properly use optional arguments

* Eliminating use of hardcoded input.nml

* Removed INPUT_STR_LENGTH references from test harness and mpp**Description**
Include a summary of the change and which issue is fixed. Please also include
relevant motivation and context. List any dependencies that are required for
this change.

Fixes # (issue)

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

### CODE REVIEW

**Comment by mathomp4** [comment]
This code is from @climbfuji

**Comment by climbfuji** [comment]
The last commit (https://github.com/GEOS-ESM/FMS/pull/29/commits/0d06e78fc388c02f8cc6ce6b080eb10db5e35620) should fix the errors that we've been seeing (and you apparently, too): `READ_ASCII_FILE: number of lines in file diag_table does not equal to size(Content(:))`

**Comment by mathomp4** [comment]
> The last commit ([0d06e78](https://github.com/GEOS-ESM/FMS/commit/0d06e78fc388c02f8cc6ce6b080eb10db5e35620)) should fix the errors that we've been seeing (and you apparently, too): `READ_ASCII_FILE: number of lines in file diag_table does not equal to size(Content(:))`

Weirdly, if anything that commit might be *causing* the error? For example, I added some prints:
```fortran
                   if(num_lines .NE. pnum_lines) then
                      write(*,*) 'MATMAT num_lines = ', num_lines, __FILE__, __LINE__
                      write(*,*) 'MATMAT pnum_lines = ', pnum_lines, __FILE__, __LINE__
                      call mpp_error(FATAL, 'READ_ASCII_FILE 2: number of lines in file '//trim(FILENAME)// &
                          ' does not equal to size(Content(:)) ' )
                   end if
```
and then:
```
FATAL from PE     0: READ_ASCII_FILE 2: number of lines in file diag_table does not equal to size(Content(:))

 MATMAT num_lines =          495 mpp_util.inc        1627
 MATMAT pnum_lines =          494 mpp_util.inc        1628
```

So it's like `pnum_lines` is one too small.

**Comment by mathomp4** [comment]
But, if I comment out the "decrement-by-one", then the `input.nml` read fails:
```
 MATMAT num_lines =           71 mpp_util.inc        1627
 MATMAT pnum_lines =           72 mpp_util.inc        1628

FATAL from PE     0: READ_ASCII_FILE 2: number of lines in file input.nml does not equal to size(Content(:))
```

So `input.nml` needs the decrement, but `diag_table` doesn't?

**Comment by mathomp4** [comment]
Okay. I might have a fix for our scenario. I need to back off all my diagnostic prints and see.

@climbfuji Can I push to your branch (not sure how fork perms work)? Or should I provide a patch and then you can put it in once I'm happy?

**Comment by climbfuji** [comment]
> Okay. I might have a fix for our scenario. I need to back off all my diagnostic prints and see.
> 
> @climbfuji Can I push to your branch (not sure how fork perms work)? Or should I provide a patch and then you can put it in once I'm happy?

Of course, please try. If you can't push I can give you write access or you can create a PR for my branch.

**Comment by mathomp4** [comment]
Grah. Or not. It looks like none of the diagnostics in `diag_table` are being written out. So we can "read" `diag_table` but it's not actually doing anything in FMS...

**Comment by climbfuji** [comment]
Maybe I need to find another solution then - I probably didn't cherry-pick all the necessary commits for the diag_table stuff to work.

**Comment by mathomp4** [comment]
I'm adding prints now to see if I can figure out what is going on. I am pretty sure things are being read. I guess I can at least push up my one fix?

**Comment by mathomp4** [comment]
Well, nuts. I guess I can't push to your branch or (more likely) I'm doing it wrong. I actually pushed to a *new* branch local to this repo called `feature/no_hardcoded_input_nml_path_for_geos_branch`. Oops. 

But the diff of my patch is:
```diff
diff --git a/diag_manager/diag_table.F90 b/diag_manager/diag_table.F90
index 82f32e3..1b90a55 100644
--- a/diag_manager/diag_table.F90
+++ b/diag_manager/diag_table.F90
@@ -231,7 +231,7 @@ MODULE diag_table_mod
   !   A simple utility has been created to help discover
   ! </DESCRIPTION>
   USE mpp_io_mod, ONLY: mpp_open, MPP_RDONLY
-  USE mpp_mod, ONLY: read_ascii_file, get_ascii_file_num_lines
+  USE mpp_mod, ONLY: read_ascii_file, get_ascii_file_num_lines_and_length
   USE fms_mod, ONLY: fms_error_handler, error_mesg, file_exist, stdlog, mpp_pe, mpp_root_pe, FATAL, WARNING, lowercase, close_file
   USE time_manager_mod, ONLY: get_calendar_type, NO_CALENDAR, set_date, set_time, month_name, time_type
   USE constants_mod, ONLY: SECONDS_PER_HOUR, SECONDS_PER_MINUTE
@@ -373,11 +373,13 @@ CONTAINS
     CHARACTER(len=9) :: amonth !< Month name
     CHARACTER(len=256) :: record_line !< Current line from the diag_table.
     CHARACTER(len=256) :: local_err_msg !< Sting to hold local error messages.
-    CHARACTER(len=DT_LINE_LENGTH), DIMENSION(:), ALLOCATABLE :: diag_table
+    CHARACTER(len=:), DIMENSION(:), ALLOCATABLE :: diag_table

     TYPE(file_description_type) :: temp_file
     TYPE(field_description_type) :: temp_field

+    integer, dimension(2) :: lines_and_length
+
     ! set up the pstat pointer
     IF ( PRESENT(istat) ) THEN
        pstat => istat
@@ -395,10 +397,11 @@ CONTAINS

     ! get the stdlog unit number
     stdlog_unit = stdlog()
-    num_lines = get_ascii_file_num_lines('diag_table', DT_LINE_LENGTH)
-    allocate(diag_table(num_lines))
+    lines_and_length = get_ascii_file_num_lines_and_length('diag_table')
+    allocate(character(len=lines_and_length(2)) :: diag_table(lines_and_length(1)))

-    call read_ascii_file('diag_table', DT_LINE_LENGTH, diag_table)
+    diag_table(:) = ' '
+    call read_ascii_file('diag_table', lines_and_length(2), diag_table)

     ! Read in the global file labeling string
     READ (UNIT=diag_table(1), FMT=*, IOSTAT=mystat) global_descriptor
```

It's entirely possible this change doesn't do what I think it does. But I could print out `diag_table` so the variable was filled. But it's like it doesn't process it correctly. More prints time!

**Comment by mathomp4** [comment]
Note: I'm essentially running the canned C12-MOM6 experiment I have in TinyBCs if you want to try and run it. (Or if you are on discover, you can just use what comes from `makeoneday.bash` if you have a c12 MOM6 run)

**Comment by climbfuji** [comment]
I just invited you as collaborator to my fms fork - please accept and try pushing to the branch again

**Comment by mathomp4** [comment]
Okay. So with the latest commit, I get two of the three diag_table outputs. I'm trying to figure out why one of them is not...outputting.

**Comment by mathomp4** [comment]
@climbfuji Okay. I think what is here works for us. I'll ping @sanAkel who is our MOM6 lead so he can maybe do some tests to make sure nothing is broken, but as far as the one MOM6 test I know how to run, it runs and is zero-diff.

Can you test on your end and make sure you are happy?

**Comment by sanAkel** [comment]
FYI @marshallward

**Comment by marshallward** [comment]
I see a lot of these changes in the current FMS.  Is this just an update of your fork?

We try to make sure that FMS `main` is working so should be OK with the MOM6 devs.  (If you do find any issues, you might see them before we do!)

**Comment by sanAkel** [comment]
> I see a lot of these changes in the current FMS. Is this just an update of your fork?
> 
Yes. As much as I know from @mathomp4

**Comment by mathomp4** [comment]
> I see a lot of these changes in the current FMS. Is this just an update of your fork?
> 
> We try to make sure that FMS `main` is working so should be OK with the MOM6 devs. (If you do find any issues, you might see them before we do!)

@marshallward Yes. This is in our rather ancient fork on a branch based on a 2019 version of FMS.

I am hoping to move GEOS to FMS 2023.04 (or 2024.0-whatever if available) "soon". "Soon" is based on our dynamics code stabilizing as changes are being made currently. I'm waiting for stability as I need to do one last sweep to make sure no more interface changes are needed (see https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/51/files).

Once that happens, I pull FMS out of GEOS, put it in Baselibs (and thus also in spack) and boom, we are now working with your code and I'll insist any FMS changes needed go through the mainline repo much like how we work with ESMF.

---

ETA: Note, I might be coming to you if I can't figure something out, but `nest_level` seemed to be the main difference even after all these years!

**Comment by climbfuji** [comment]
A word of caution here, we still have problems with this branch. I'd very much prefer to move straight to fms@2023.04, but as @mathomp4 said this may be a while.

**Comment by sanAkel** [comment]
> A word of caution here, we still have problems with this branch. I'd very much prefer to move straight to fms@2023.04, but as @mathomp4 said this may be a while.

As far as the ocean component of GEOS coupled model, i.e., MOM6 is concerned, there is *no* problem moving to _latest_ FMS version - I'm sure @mathomp4 already made that clear to you @climbfuji.

**Comment by mathomp4** [comment]
All my testing shows this and https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/100 are zero-diff for GEOSgcm v11 and v12. Once @climbfuji and @cmgas confirm these changes are good on their end, merges and releases will be made.

**Comment by cmgas** [comment]
I am still encountering errors with the last changes (when initializing geometries with JEDI), so please don't merge yet

```
FATAL from PE    45: check_nml_error in fms_mod:  Unknown namelist, or mistyped namelist variable in namelist fv_core_nml, (IOSTAT =         5010 )
```

**Comment by climbfuji** [comment]
This means that a namelist entry in your setup is not supported by this version of fms. Unlikely this will require any changes in fms, but rather in the JEDI code. But better to wait, I agree ...

**Comment by mathomp4** [comment]
> I am still encountering errors with the last changes (when initializing geometries with JEDI), so please don't merge yet
> 
> ```
> FATAL from PE    45: check_nml_error in fms_mod:  Unknown namelist, or mistyped namelist variable in namelist fv_core_nml, (IOSTAT =         5010 )
> ```

Dang.

Yeah, it's possible JEDI is trying to call something our FMS doesn't have as a namelist. Grah. :(

**Comment by cmgas** [comment]
I ran both forecast cases on the same files / work directory and am seeing this:
- using the `GEOSgcm.x` exe works just fine
- using the jedi forecast exe fails with the error above

**Comment by mathomp4** [comment]
> I ran both forecast cases on the same files / work directory and am seeing this:
> 
> * using the `GEOSgcm.x` exe works just fine
> * using the jedi forecast exe fails with the error above

Hmm. Is the JEDI forecast `input.nml` available? It must be (at least) something in the `fv_core_nml` section per that error.

**Comment by cmgas** [comment]
That's the crazy thing: they are the same `input.nml`!

**Comment by mathomp4** [comment]
> That's the crazy thing: they are the same `input.nml`!

Well, huh. Is the dynamics version between the two tests the same? That namelist is called by `fv_control.F90` and the [one in GEOS](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/blob/4bac7bb49269b3dc5ba65bac41e396c670500bc8/model/fv_control.F90#L661) is quite different than the one in, for example, ["mainline" FV](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/0b42dc30ac83a28ea1867e408d11714d01bfdcb4/model/fv_control.F90#L934).

Perhaps if the dynamics are different, a namelist entry in the GEOS FV was *removed* in newer FV?

**Comment by cmgas** [comment]
Thanks for the pointer! I found a key that still exists in our nml but not the code, testing now

**Comment by cmgas** [comment]
Alright, I managed to fix that `mistyped namelist variable` error (and pushd to Dom's branch in fv3-jedi) but am now hitting the next one: yet another 
```
1985: FATAL from PE     0: get_ascii_file_num_lines: File input.nml does not exist.
``` 
when I try to provide my own namelist with JEDI, the error happens [there](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/blob/9b9c6f256a76b4822e9a064f43c838399be0958f/model/fv_control.F90#L733). 
Is this not supposed to read the provided nml too? 
If I comment out this line, my tests pass again. @mathomp4 would you be able to tell me what it does?

**Comment by mathomp4** [comment]
> Alright, I managed to fix that `mistyped namelist variable` error (and pushd to Dom's branch in fv3-jedi) but am now hitting the next one: yet another
> 
> ```
> 1985: FATAL from PE     0: get_ascii_file_num_lines: File input.nml does not exist.
> ```
> 
> when I try to provide my own namelist with JEDI, the error happens [there](https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/blob/9b9c6f256a76b4822e9a064f43c838399be0958f/model/fv_control.F90#L733). Is this not supposed to read the provided nml too? If I comment out this line, my tests pass again. @mathomp4 would you be able to tell me what it does?

Hmm. Are you using the new `alt_input_nml_path` thing that @climbfuji added here? Maybe FV doesn't know about that option and so it's looking for a file called `input.nml` in the working directory?

I'm not sure how that works as in GEOS we just provide `input.nml` where FMS "expects" it.

**Comment by climbfuji** [comment]
I am looking at this now. Stay tuned

**Comment by climbfuji** [comment]
> I am looking at this now. Stay tuned

solved I think - will push an update momentarily

**Comment by climbfuji** [comment]
I just pushed https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/100/commits/20fc76a3cec11d3949eb1893c472b297a7f24b45

With this I could run the geometry ctest in JEDI.

@mathomp4 Would you mind looking at the logic please, and checking if this still works for you (sorry that I have to ask you for even more testing)?

**Comment by mathomp4** [comment]
@climbfuji I'll build-and-test now. Back in a bit...

**Comment by mathomp4** [comment]
> @climbfuji I'll build-and-test now. Back in a bit...

Well, in all my testing, it looks like your latest FMS commit doesn't harm GEOS (in the test cases I ran at least). So I think it is good to go.

**Comment by climbfuji** [comment]
@mathomp4 I think this is ready for review? I've opened up https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/pull/100 for reviews just now.

**Comment by mathomp4** [comment]
@climbfuji Did @cmgas confirm the change works for her? If so, I can then work on getting it into releases.

**Comment by climbfuji** [comment]
> @climbfuji Did @cmgas confirm the change works for her? If so, I can then work on getting it into releases.

Yes - but let @cmgas speak for herself and confirm :-)

**Comment by cmgas** [comment]
Sorry, yes now everything works as I expect! Thank you

**Comment by mathomp4** [comment]
@cmgas Good to hear. I'll start working on releases!

**Pull request merged**
